#server.port=9977
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/asset-management-system?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://10.20.2.50:8123/test
    password: 123456
    initialSize: 10
    maxActive: 100
    minIdle: 10
    maxWait: 6000
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.wyu.tt16clickhouse.entity
server:
  port: 9970

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    root: info
  file:
    path: ./logs